rest:
  auth-open: true #jwt鉴权机制是否开启(true或者false)
  sign-open: true #签名机制是否开启(true或false)
wx:
 pay:
  notify_host: http://246q2604o1.qicp.vip
  notify_url_customer_pay_pickup: /customer-pay/pickup #到店自提支付回调
  notify_url_customer_pay: /customer-pay #商家发货支付回调
  notify_url_customer_pay_diff: /customer-pay/money-diff #补差价支付回调
jwt:
  header: Authorization   #http请求头所需要的字段
  secret: mySecret        #jwt秘钥
  expiration: 604800      #7天 单位:秒
  auth-path: auth/login          #认证请求的路径
  logout-path: auth/logout  #退出登录
  md5-key: randomKey      #md5加密混淆key

server:
  port: 80 #项目端口

mybatis-plus:
  mapper-locations: classpath*:com/soft/ware/**/mapping/*.xml
  typeAliasesPackage: com.soft.ware.**.model
  
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true #开启驼峰
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
    call-setters-on-nulls: true # 返回map是空字段也返回
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用

spring:
  datasource:
      url: jdbc:mysql://192.168.10.128:3306/pau?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
      username: root
      password: Hzcx_root
      filters: log4j,wall,mergeStat
  devtools:
    restart:
      enabled: true #是否开启开发者工具（true/false）
      additional-paths: src/main/java
      exclude: static/**,WEB-INF/view/**
  redis:
    database: 0
    host: 192.168.10.6
    port: 6379
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss #在实体时间类型上添加 @JsonFormat(pattern="yyyy-MM-dd HH:mm")
logging:
  level.root: info
  level.com.soft.ware: debug
  path: logs/
  file: pau-rest.log